#!/bin/bash
#SOURCE_HOME=/home/ark/public_html/pj
SOURCE_HOME=/home/ark/books/bpp/pj
JDK_HOME=/opt/jdk1.5.0_22
SOURCEPATH=$SOURCE_HOME/lib
BOOTCLASSPATH=$JDK_HOME/jre/lib/rt.jar
DOCDIR=$SOURCE_HOME/doc
#LINKURL1=file://$JDK_HOME/docs/api
LINKURL1=http://java.sun.com/j2se/1.5.0/docs/api
OVERVIEWFILE=$SOURCEPATH/overview.html
if [[ -d $DOCDIR ]]
then
    rm -r $DOCDIR/*
else
    echo "Documentation directory $DOCDIR does not exist."
    exit 1
fi
javadoc -sourcepath $SOURCEPATH -bootclasspath $BOOTCLASSPATH -d $DOCDIR -use -splitindex -doctitle "THE PARALLEL JAVA LIBRARY" -link $LINKURL1 -windowtitle "Parallel Java Library Documentation" -bottom "<FONT SIZE=\"-2\">Copyright &copy; 2005-2010 by Alan Kaminsky. All rights reserved. Send comments to ark</FONT><FONT SIZE=\"1\" COLOR=\"#FFFFFF\">&shy;</FONT><FONT SIZE=\"-2\">&#64;</FONT><FONT SIZE=\"1\" COLOR=\"#FFFFFF\">&shy;</FONT><FONT SIZE=\"-2\">cs.rit.edu.</FONT>" -overview $OVERVIEWFILE @packages.txt >/dev/null
